FORMAT: 1A
HOST: http://localhost/

# API DOCUMENTATION

## Create Account [/register]

### Step 1 [POST]

+ Request (application/json)

        {
            "name": "ombella2ela2ombella2ela2ombella2ella2ah",
            "email: "dd@dd.com",
            "password": "cjhsgdfshfkjdhjkfsdf;",
        }

+ Response 200 (application/json)

        {
            "error": false,
            "message": "Verification link sent to your email."
        }

### Step 1 - invalid or used email [POST]

+ Request (application/json)

        {
            "name": "Mohamed Darwish",
            "email: "dd@dd.com",
            "password": "cjhsgdfshfkjdhjkfsdf;",
        }

+ Response 400 (application/json)

        {
            "error": true,
            "message": "This email is already registered."
        }
        
### Step 2 [POST] 

+ Request (application/json)

        {
            "email: "dd@dd.com",
            "token": "dsahjdgdshfjhshdkhfjsdfhjdshjf",
        }

+ Response 201 (application/json)

        {
            "error": false,
            "message": "Account has been activated successfully."
        }
        
### Step 2 - expired or invalid token [POST] 

+ Request (application/json)

        {
            "email: "dd@dd.com",
            "token": "dsahjdgdshfjhshdkhfjsdfhjdshjf",
        }

+ Response 400 (application/json)

        {
            "error": true,
            "message": "Session Expired!"
        }
        

## Login [/login]

### Login with valid data [POST]

+ Request (application/json)

        {
            "email: "dd@dd.com",
            "password: "1232434546575676767"
        }
        
+ Response 200 (application/json)

        {
            "error": false,
            "token": "54787878787sdf78sdfsdjfajshdf"
        }
 
### Login with invalid data [POST]

+ Request (application/json)

        {
            "email: "dd2@dd.com",
            "password: "12324345e46575676767"
        }
        
+ Response 400 (application/json)

        {
            "error": true,
            "message": "Invalid email or password."
        }
        
        
        
## Product search [/search?q=iPhone]

### Search [GET]

+ Response 200 (application/json)

        {
            "error": false,
            "data": [{"name":"iPhone", "price":1, color:"bamby"}]
        }

## Products [/products/{product_id}]

### Create [POST]

+ Request (application/json)

    + Headers
        Authentication: "authtoken"
    
    + Body

        {"name":"iPhone", "price":1, color:"bamby"}
        
+ Response 201
        
        {
            "error": false,
            "message": "Product created successfully",
            "product": {"id":"1", "name":"iPhone", "price":1, color:"bamby"}
        }

### Update [PUT]

+ Parameters

    + product_id (string)
    
+ Request (application/json)

    + Headers
        Authentication: "authtoken"
    
    + Body

        {"name":"iPhone", "price":1, color: "pink"}
        
+ Response 200
        
        {
            "error": false,
            "message": "Product updated successfully",
            "product": {"id":"1", "name":"iPhone", "price":1, color:"pink"}
        }

### Delete [DELETE]

+ Parameters

    + product_id (string)

+ Request (application/json)

    + Headers
        Authentication: "authtoken"
    
+ Response 204

        {
            "error": false,
            "message": "Product deleted successfully"
        }

### Get Single Product [GET]

+ Parameters

    + product_id (string)

+ Response 200

        {
            "error": false,
            "data": {"id":"1", "name":"iPhone", "price":1, color:"pink"}
        }

### Get All Products [GET]

+ Response 200

        {
            "error": false,
            "data": [{"id":"1", "name":"iPhone", "price":1, color:"pink"}]
        }